### ISSUE TITLE
How to run and test this project

### ISSUE THREAD

**Issue by Khunpisit** [joncody/wsrooms#1]
Hi, I want to run and test this project. Maybe I will use it.
I try to build all go files and run app.go and then open localhost:8080 but I didn't see anything on the browser.

log from app.go
> 2017/09/21 15:02:51 websocket: close 1001 (going away)
>2017/09/21 15:16:54 read tcp [::1]:8080->[::1]:57220: i/o timeout
>2017/09/21 15:18:07 websocket: close 1001 (going away)
>2017/09/21 15:18:10 websocket: close 1001 (going away)
>2017/09/21 15:18:14 websocket: close 1001 (going away)
>2017/09/21 15:34:55 websocket: close 1001 (going away)
>2017/09/21 15:35:04 websocket: close 1001 (going away)
>2017/09/21 15:37:59 websocket: close 1001 (going away)

How to run and test this project?
Please explain the step.

Thank in advance.

**Comment by joncody** [comment]
Open up the console in the browser.  You can access the wsrooms object via the variable `socket`.
