### ISSUE TITLE
Example to join and send messages

### ISSUE THREAD

**Issue by changeloghero** [joncody/wsrooms#3]
Hi, 
I'm a little confused how this works.

I created 2 browser windows and joined the same room but I got different room.id()'s back.
```
room = socket.join("blah")
room.id();
```
The call to room.id(); returned 2 different guids.

Can you please give an example of joining a room, sending a message etc.

**Comment by joncody** [comment]
All `room.id()` calls return the unique identifier for you as a user.  A UUID is assigned to each individual WebSocket connection after successfully upgrading.  Think of it as a shortcut to calling `rootroom.id()` in some way.  `room.name` is unique to each room.
