### ISSUE TITLE
How do you emit/broadcast to everyone in a room

### ISSUE THREAD

**Issue by randallmlough** [joncody/wsrooms#4]
Huge thanks for this project! 

So how exactly can I get everyone who is a member of a room to receive a message? I can get everyone in the "root" room to receive a message, but when I have a couple _users_ join a room I can't seem to get everyone in that room to receive messages.

to use your example, I modified the hello event 

```
wsrouter.Emitter.On("hello", func (c *wsrouter.Conn, msg *wsrouter.Message) {
    c.Emit(msg)
})
```

How I've been testing
user1: `socker.name` -> "root"
user1: `socket.send("hello","message 1")`
user2: receives –> "message 1"
user3: receives –> "message 1"

user1: `room = socket.join("foo")`
user2: `room = socket.join("foo")`
user1: `room.send("hello","private room message 1")`
user2: receives nothing
also tired...
user1: `socket.send("hello","private room message 1", "main") // I understand that "main" in this example is really just the user id, but tried it anyways`
user2: receives nothing
but I can send direct messages
user2: `id()` -> "abc123"
user1: `socket.send("hello","direct message","abc123")`
user2: <-  "abc123"

What am I missing here?

**Comment by joncody** [comment]
The problem was twofold.

**Comment by randallmlough** [comment]
Thanks for the quick reply.

I see `members()` now updates effectively, but I still can't get a room outside of "root" to receive messages.

if users 1,2,3 and have joined room foo `room = socket.join("foo")` what is the proper method to get users to receive messages in that room?
user1: `room.send("hello","testing")` but still user 2 and 3 never received the messages. I confirmed in the app logs that it was receiving the messages
logs:
```
2019/02/05 17:04:11 &{4 root 5 hello 0  36 0ebf3819-c410-433c-9e82-acd47b3ab34e 7 [116 101 115 116 105 110 103]}
2019/02/05 17:05:12 &{4 foo 5 hello 0  36 0ebf3819-c410-433c-9e82-acd47b3ab34e 10 [116 101 115 116 105 110 103 49 50 50]}
```
Thanks for your help here

**Comment by joncody** [comment]
For now, it's left to the server side code as shown in the updated example directory within app.go.

**Comment by joncody** [comment]
For now room direction is event based, left to the server, as shown in the updated example directory within app.go.

`wsrooms.RoomManager[msg.Room].Emit(c, msg)`

**Comment by joncody** [comment]
Currently message direction is event based - some refinements definitely ought to be made within the coming days.

`wsrooms.RoomManager[msg.Room].Emit(c, msg)`

**Comment by joncody** [comment]
Currently message direction is entirely manual and event based - some refinements definitely ought to be made within the coming days.

`wsrooms.RoomManager[msg.Room].Emit(c, msg)`

**Comment by joncody** [comment]
Currently message direction is entirely manual and event based with the exception of the root room - some refinements definitely ought to be made within the coming days.

`wsrooms.RoomManager[msg.Room].Emit(c, msg)`

**Comment by joncody** [comment]
```
wsrooms.Emitter.On("hello", func (c *wsrooms.Conn, msg *wsrooms.Message) {
		c.Emit(msg)
                // OR
                if msg.Room == "foo" {
                    c.Emit(msg)
                }
                // AND to send back to the sender
		c.Send <- MessageToBytes(msg)
})
```
The reason being we sometimes need to check `c.Cookie` when dealing with administrative methods.

**Comment by joncody** [comment]
https://github.com/joncody/wsrooms/commit/15aa3bb6e8e84a32e98f8b50304cfbc1a2f8bfda

**Comment by joncody** [comment]
https://github.com/joncody/wsrooms/commit/ce0113fe9c9f69c55c2be1c5c0852dfb8033ee23

Whoops, should be `> 0`.  What this means is if we are not listening for a particular event on the server side, then the message will be broadcast to the room.  If there is even one listener, however, then one will have to manually call `c.Send(msg)` at least once in one of the listeners to broadcast.
